Error: D-Optimality: RRQR will only return min(n,p) values (the rank of matrix X)
Repeatedly remove rank(X) rows from X and get the next rank(X) rows

 On branch master
 Your branch is up to date with 'origin/master'.

 Changes to be committed:
	modified:   optimal_design.py
	modified:   ../../tests/test_ExperimentDesign.py