Error: first element in S optimality should be random from 1 to N. missing size argument. For previous applications, it will return 0. However, this should not affects the accuracy of the algorithm since the first element should be random anyway
 On branch master
 Your branch is up to date with 'origin/master'.

 Changes to be committed:
	modified:   optimal_design.py