Error: checking cls weight, fit_method need to be lower case  On branch master  Your branch is up to date with 'origin/master'.
 Changes to be committed:
	modified:   examples/sparse_poly/fix_DoE_ols.py