change results recording approach in adaptive simulation
Original: active_basis = collections.deque(maxlen=3):
	Error: when overfitting detected, active_basis.pop() until there
	is one element. setting p = p-1 or p = p-2 accordingly

	In the new iteration, new samples are draw (based on
	active_basis[-1] if optimality, note only one element in
	active_basis now). Then these new sampels together with old
	samples are used to run LASSO for PCE.deg == p, get the new
	active_basis for PCE.deg ==p.

	Error: after finishing this step, two active sets for PCE.deg ==p exist in active_basis since the old one was not popped

Current: For all calculating results, generate [0,] * (plim[1]+1) list
	at each iteartion, update the res[p] based on current PCE.deg
	when overfitting detected, set p = max(plim[0], p-2) and then
	erase all results corresponding to PCE.deg higher than current p

 On branch master
 Your branch is up to date with 'origin/master'.

 Changes to be committed:
	modified:   examples/sparse_poly/adaptive_DoE_lasso.py
	modified:   museuq/simParameters.py
	modified:   museuq/surrogates/polynomial_chaos_expansion.py