Error: Wrong D-optimality indice returned:
Should return the indice in the original X, but those in X_ directly
after qr factorization
 On branch master
 Your branch is up to date with 'origin/master'.

 Changes to be committed:
	modified:   optimal_design.py