Error: self.min_r2 need to be checked only when R2 values are given  On branch master  Your branch is up to date with 'origin/master'.
 Changes to be committed:
	modified:   simParameters.py