error: pred file with E7 sampels  On branch master  Your branch is up to date with 'origin/master'.
 Changes to be committed:
	modified:   stochastic_AdapPCE.py