Error: while loop for D optimality, X_
 On branch master
 Your branch is up to date with 'origin/master'.

 Changes to be committed:
	modified:   optimal_design.py