error: active_basis_path.append(active_basis[p])  On branch master  Your branch is up to date with 'origin/master'.
 Changes to be committed:
	modified:   Franke/adaptive_DoE_lasso.py
	modified:   Ishigami/adaptive_DoE_lasso.py
	modified:   four_branch_system/adaptive_DoE_lasso.py
	modified:   sparse_poly/adaptive_DoE_lasso.py