error: str.upper() forget ()  On branch master  Your branch is ahead of 'origin/master' by 2 commits.    (use "git push" to publish your local commits)
 Changes to be committed:
	modified:   optimal_design.py